[project]
name = "flint-conver-cronos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chardet>=5.2.0",
    "dbf>=0.99.11",
    "dbfpy3>=4.2.3",
    "dbfread>=2.0.7",
    "pandas>=2.3.3",
    "simpledbf>=0.2.6",
]
